### ISSUE TITLE
Vardecl assignemnt count mismatch

### ISSUE THREAD

**Issue by ghost** [rsc/grind#3]
... duplicate, sorry.

**Comment by dmitshur** [comment]
You're not the only one. From this morning,

![go get without u](https://cloud.githubusercontent.com/assets/1924134/6357245/cd354148-bc17-11e4-9883-77939358dc37.png)

I blame the README for not including `-u`. It's a bad default because it's unpredictable (results depends on user's past state of GOPATH workspace).

**Comment by rsc** [comment]
The readme says go get [-u] now.
People need to think about whether to use -u or not, but at least now there's a reminder.
